### ISSUE TITLE
renderer process crash in cog container on Toradex Verdin iMX8M-Plus

### ISSUE THREAD

**Issue by escherstair** [commontorizon/Containerfiles#17]
I used cog container from [commontorizon/cog:3.3.1](https://hub.docker.com/layers/commontorizon/cog/3.3.1/images/sha256-bfe44d6ecdd10e699173db391447fed208f8f077c2b5c18590b58d11eea8ed59?context=explore) on my Verdin iMX8M-Plus running Torizon OS 6.7.0+build.18

I launch it using my docker compose
```
kiosk:
    command: http://172.17.0.1:3000/
    depends_on:
      weston:
        condition: service_started
    device_cgroup_rules:
      - c 199:* rmw
    environment:
      MACHINE: null
      ALSA_CARD: audiohdmi
    image: commontorizon/cog:3.3.1
    platform: linux/arm64
    security_opt:
      - seccomp:unconfined
    shm_size: 4Gb
    privileged: true
    volumes:
      - source: /tmp
        target: /tmp
        type: bind
      - source: /var/run/dbus
        target: /var/run/dbus
        type: bind
      - source: /dev/galcore
        target: /dev/galcore
        type: bind
```

On http://172.17.0.1:3000/ there is my application (it works if I use torizon/chromium container).
The renderer process crashed with the following errors
![immagine](https://github.com/user-attachments/assets/61a32d2c-0933-47be-905f-a96d8820005b)

Is there any missing parameter in my `docker-compose.yml`?
